# Changes here will be overwritten by Copier
_commit: 42e01c1
_src_path: https://github.com/python-project-templates/base.git
add_extension: js
email: 3105306+timkpaine@users.noreply.github.com
github: python-project-templates
project_description: A JavaScript-Python project template
project_name: js template
python_version_primary: '3.11'
team: Python Project Template Authors
